apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: crypto-currency-api
    app.kubernetes.io/managed-by: Helm
  name: crypto-currency-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: crypto-currency-api
status:
  loadBalancer: {}
