name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-push-to-ecr:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: crypto-currency-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo $REGISTRY
        echo $REPOSITORY
        echo $IMAGE_TAG
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
        -t $REGISTRY/$REPOSITORY:latest .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: EKS Helm Deploy
      uses: peymanmortazavi/eks-helm-deploy@v2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS__KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        cluster-name: crypot-eks-iPjZsA41
        namespace: default
        name: crypto-currency-api
        chart-path: helm-charts

#    - name: Deploy Helm Chart
#      uses: deliverybot/helm@v1
#      env:
#        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
#      with:
#        release: api
#        namespace: default
#        chart: crypto-currency-api
#        token: ${{ github.token }}
