name: Build and Deploy
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-push-to-ecr:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: crypto-currency-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo $REGISTRY
        echo $REPOSITORY
        echo $IMAGE_TAG
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
        -t $REGISTRY/$REPOSITORY:latest .
        docker push $REGISTRY/$REPOSITORY --all-tags

    - name: Deploy Helm Chart
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        command:  helm upgrade crypto-currency-api helm-charts/.

    - name: Get URL
      id: url
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        command: kubectl get svc crypto-currency-api -o json | jq -r '.status.loadBalancer.ingress[0].hostname'

    - name: Print Response
      run: echo "Response was ${{ steps.url.outputs.response }}"

    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: crypto-alerts
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: crypto-alerts
        status: FAILED
        color: danger
