name: Build and Deploy
on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-push-to-ecr:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: crypto-currency-api
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo $REGISTRY
        echo $REPOSITORY
        echo $IMAGE_TAG
        docker build -t $REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$IMAGE_TAG \
        -t $REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:latest .
        docker push $REGISTRY.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$IMAGE_TAG

    - name: Deploy Helm Chart
      uses: deliverybot/helm@v1
      env:
        KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
      with:
        namespace: default
        chart: crypto-currency-api
        token: ${{ github.token }}
